### ISSUE TITLE
Add autobinding for React methods

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#104]
### Expected behaviour

React methods are bound to the instance of the class. For example, `this.doThing()` in a component should be in the context of the component.

This functionality is implemented in [dan1elhughes/yaab](https://github.com/dan1elhughes/yaab).

### Actual behaviour

Methods are not called in the component's context.

### Steps to reproduce behaviour

Add a component method which refers to `this` without calling `this.thing = this.thing.bind(this)` in constructor.

**Comment by ShaunBulbrook** [comment]
@morena needs more time to work on this. 

@peasandwell to catch up today and update this issue.
