### ISSUE TITLE
Replace margin-left animation with translation

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#108]
The CSS animations are struggling to keep to a smooth 60fps on both the target iPad device and my development machine. Looking at [this article](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/), it looks like we should be animating `translateX` instead of `margin-left`. I can see in the code that this is implemented but commented out, did it not work?

**Comment by Boxface** [comment]
Reworked the progress bar so it does not use a second animation as it was struggling when you change from margin-left to translate.

New bar looks smooth with the translateX
