### ISSUE TITLE
Define UX for first time use

### ISSUE THREAD

**Issue by peasandwell** [HeathWallace/coinface#113]
When the user first fires up the app, it needs to collect some information before it can be put to use. The UX needs to be defined to capture this data.

Probably the easiest approach for this would be to walk the user through all of the options in the settings, including wallet address and trust setting.

**Comment by ArghZombies** [comment]
OK, a prototype containing two different possible routes. Personal preference is option 2 as it shows the information In Context. 

I imagine this would require the use of a 3rd party onboarding solution, something like http://bootstraptour.com/ perhaps? Unless it's quicker / easier to build it bespoke.

https://sketch.cloud/s/aMlnp/all/page-1/start-page/play

**Comment by peasandwell** [comment]
After a discussion with the group, I believe the general consensus is to go with option 2.

I have opened #147 to implement this, and will close this ticket as it's now completed.
