### ISSUE TITLE
Perceived wait time should be minimised

### ISSUE THREAD

**Issue by ShaunBulbrook** [HeathWallace/coinface#18]
### As a user I want to minimise the perceived wait time so that my customers don't feel held up.

**Comment by ShaunBulbrook** [comment]
Recommend targeting this for the Berkswell release.

**Comment by dan1elhughes** [comment]
What's the acceptance criteria for this?

**Comment by ShaunBulbrook** [comment]
This was brought up by Leo for the preemptive concern over the transaction time. 
Current plan is to write the requirements in the Berkswell planning session. 

Will probably need @ArghZombies to help with this.

**Comment by dan1elhughes** [comment]
Covered in #76
