### ISSUE TITLE
Vendor initial setting need to be requested at app startup.

### ISSUE THREAD

**Issue by ShaunBulbrook** [HeathWallace/coinface#27]
Vendor settings should be set at the application's initial startup.
- If the vendor is starting the application for the first time, they should be prompted to enter their settings.
- The application should store the settings for use in future sessions.
- After settings have been entered, the application should continue to the main screen.

The vendor should be able to set the following at startup:
- Wallet Address
- Contract Address
- Trust Level
- Identity Resolver address (optional)
- Currency symbol

**Comment by ShaunBulbrook** [comment]
Child of #12

**Comment by ShaunBulbrook** [comment]
@dan1elhughes can you update the status of this issue?

**Comment by ShaunBulbrook** [comment]
Vender address is being hardcoded in the environment variable for now. - Bumping this into next release.

**Comment by ShaunBulbrook** [comment]
Blocked by #27

**Comment by ShaunBulbrook** [comment]
#94 has been cleared and this should now be good to go.

**Comment by ShaunBulbrook** [comment]
@ArghZombies @leoheathwallace
Could we grab some input from you when you have time around the UX for this?

**Comment by ShaunBulbrook** [comment]
Ticket updated to apply to all settings and not just the wallet address

**Comment by peasandwell** [comment]
Closing this ticket as we need to go through a much fuller process to get this included correctly. See #113
