### ISSUE TITLE
Trust setting component

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#43]
## `<TrustSetting/>`

A mechanism by which the user can configure a preference between waiting a long time for high confidence or short time with low confidence in transactions validity.

This component should be created in Storybook, with designs TBD.

### Input props

- `value`: the currently entered trust setting

### Output props

- `onChange(newValue)`: called when the value in the input is changed by the user

**Comment by ShaunBulbrook** [comment]
@Gazzah-86 wanted to pick this one up.

**Comment by ArghZombies** [comment]
I've been thinking about this component, and think that the style to aim for is not to include number entry at all, but to opt for an 'Acceptable Risk' selection - low risk, medium risk and higher risk (or a few states inbetween). 

The user doesn't necessarily need to know the numerical figure the Trust is based on, they just need to know the meaning behind it. So we can define what we believe is a good Trust figure for 'Low Risk' and the same for 'High Risk' and the user can select their trust setting by Risk instead.

For example: 

![image](https://user-images.githubusercontent.com/36080617/36269483-39dbc0da-1271-11e8-80ff-3f7878b4b6cf.png)

**Comment by dan1elhughes** [comment]
@ArghZombies Good idea! Shall we stick with 5 options? We can tweak the underlying values from testing the live app.

**Comment by ShaunBulbrook** [comment]
One action I have from the last catch-up is the de-scoping of trust indicator.
I'll keep this up for the Applewood release for now, but I've updated the priorities.

**Comment by ShaunBulbrook** [comment]
De-scoping this for Applewood. - Some discovery needs to be done to see how the trust indication journey will be completed.

Moving to Berkswell.

**Comment by ShaunBulbrook** [comment]
Mark to look into the design

**Comment by Flujible** [comment]
Is in branch https://github.com/Flujible/ethereum-pos/tree/feature/43-Trust-setting-component
Still need to add CSS, but the main JSX etc is done

**Comment by ShaunBulbrook** [comment]
Presently being looked into by @louislloydjudson
