### ISSUE TITLE
Environment utility should take Storybook mode into account

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#62]
### Expected behaviour

The `util/Environment` singleton doesn't throw errors when running Storybook.

### Actual behaviour

It throws errors because Storybook only passes in environment variables starting with `STORYBOOK_` into the app.

### Steps to reproduce behaviour

`npm run storybook`

**Comment by peasandwell** [comment]
It looks like this has been resolved on Storybook's side - https://github.com/storybooks/storybook/issues/2668

It's currently in a pre-release so I haven't been able to verify if this fixes the issue.

**Comment by ShaunBulbrook** [comment]
@dan1elhughes can you offer any help with this.
