### ISSUE TITLE
Deploy new instance of smart contract which rejects incoming transfers

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#65]
### Expected behaviour

The contract will return an error if you attempt to send currency to it.

### Actual behaviour

The contract accepts the currency and the money is lost forever. Fix by adding [this library method](https://openzeppelin.org/api/docs/ownership_CanReclaimToken.html).

### Steps to reproduce behaviour

Send any ERC20 token to the smart contract address.

**Comment by ShaunBulbrook** [comment]
Would be keen to either pair, or have you do this in a seminar so the wider team can get a look-in at solidity.

**Comment by dan1elhughes** [comment]
OpenZeppelin/zeppelin-solidity#748

**Comment by ShaunBulbrook** [comment]
Descoping, the current tokens are still effective for the testing. We don't want to burn more of our ETH budget deploying new contracts when the issue is in-hand. 

We should perhaps look instead at setting up the new contract on the test-net. @dan1elhughes any thoughts?
