### ISSUE TITLE
Reducer unit tests

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/coinface#83]
The reducers in the Redux section of the app should be unit tested to ensure they are functioning correctly.

https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md

**Comment by dan1elhughes** [comment]
https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md

**Comment by peasandwell** [comment]
@dan1elhughes  would you say this has been completed by #95 ?

**Comment by peasandwell** [comment]
As recommended by @ShaunBulbrook I'm currently using the coverage tool by Jest to fill in any gaps I feel are required to complete this task.

**Comment by peasandwell** [comment]
I've tackled this one as much as I can (see #136 for a PR). Now developers should be able to do `npm test-watch -- --coverage` to see where there are gaps for writing unit testing.

The biggest gaps are for more complicated actions/reducers and the API calls, which may need the original author to look into writing unit tests... @dan1elhughes where do you think we should take it from here?
