### ISSUE TITLE
Ability to mark entire transaction as completed

### ISSUE THREAD

**Issue by peasandwell** [HeathWallace/coinface#88]
Users should be able to mark individual transactions as "complete" (i.e. item has been paid for and item has been given to the buyer).

Upgrade to be added onto the `<Transaction />` component

- [ ] UX
- [ ] Unstyled implementation
- [ ] Design
- [ ] Implementation of design

**Comment by ShaunBulbrook** [comment]
@leoheathwallace

**Comment by dan1elhughes** [comment]
Added task checklist to description

**Comment by ShaunBulbrook** [comment]
Descoped from Berkswell because of requirements change.

**Comment by peasandwell** [comment]
These requirements have evolved into a vendor product categorisation task, I will close this ticket as essentially irrelevant now. A new one may open in the future once we discover the requirements for the sales categorisation task.
