### ISSUE TITLE
Error states for AddressInput

### ISSUE THREAD

**Issue by peasandwell** [HeathWallace/coinface#91]
Currently there is no validation on the `<AddressInput />` component, this means that users can enter a completely invalid wallet address and be completely unaware.

We need to design and implement error states for the `<AddressInput />` if there:
- is no value entered for the component
- an invalid entry is on the component

**Comment by m-potts** [comment]
Error state design has now been uploaded to the Invision prototype 
![theme 1 - settings error state](https://user-images.githubusercontent.com/36927968/37535758-9c353cf8-2940-11e8-8e4d-b45000b18551.png)

**Comment by ShaunBulbrook** [comment]
@peasandwell to pick up again.
